http://localhost:4000/

###
http://localhost:4000/status

###
http://localhost:4000/blocks

###
POST http://localhost:4000/block

{
    "message": "Block Data!"
} 

###     
http://localhost:4000/block/00d5395e905f6f20f4a3558e73cb73bad4e0180b832c34fe1a6ff7a6a6ec8a54

###
http://localhost:4000/balance/david?total=true

###
http://localhost:4000/mempool

###
POST http://localhost:4000/transaction

{
    "to": "david",
    "amount": 5
}